#!/usr/bin/env python3
"""Render the measured scaling curves as committed SVG artifacts.

Every data point below is transcribed verbatim from ``docs/perf-notes.md`` --
the honest performance record measured by the ``benchmarks/`` harness. This
script is the provenance for the chart artifacts under ``docs/perf/``: a
reviewer can diff the series here against the perf-notes tables, and the charts
are regenerated by running ``python scripts/generate_perf_charts.py`` whenever
the recorded numbers change. Pure stdlib -- no plotting dependency, per the
project's stdlib-only rule.
"""

from __future__ import annotations

import math
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Measured data (from docs/perf-notes.md). Machine: Apple M5 (4P+6E), macOS,
# CPython 3.14.2 / 3.14.2t. Ratios are the portable signal.
# ---------------------------------------------------------------------------

# Phase 2 -- replication throughput vs worker count, free-threaded build.
REPLICATION_FREETHREADED = {
    "threads": [(2, 1.33), (4, 1.29), (8, 0.98)],
    "processes": [(4, 2.80), (8, 3.68), (10, 3.70)],
    "interpreters": [(4, 2.67), (8, 2.92)],
}

# Phase 2 -- replication throughput vs worker count, GIL build.
REPLICATION_GIL = {
    "processes": [(1, 0.94), (2, 1.87), (4, 2.86), (8, 3.85), (10, 3.83)],
    "interpreters": [(4, 3.01), (8, 4.31)],
}

# Phase 3 -- shard scaling vs sequential reference (3.14.2t).
PDES_SHARD_SCALING = {
    "shards (3.14.2t)": [(1, 1.06), (2, 1.10), (4, 0.95), (8, 0.45)],
}

# Phase 3 -- lookahead degradation, 4-shard ring, local event spacing 0.25.
# x is the lookahead / mean-spacing ratio; y is wall clock vs L=4x sequential.
PDES_LOOKAHEAD = {
    "wall clock vs L=4x": [(4, 0.10), (2, 0.05), (1, 0.02), (0.5, 0.01), (0.25, 0.01)],
}

# Colour-blind-safe series palette (Okabe-Ito subset).
SERIES_COLORS = ["#0072b2", "#d55e00", "#009e73", "#cc79a7"]

WIDTH, HEIGHT = 680, 420
MARGIN_LEFT, MARGIN_RIGHT = 64, 150
MARGIN_TOP, MARGIN_BOTTOM = 48, 56


def _nice_max(value: float) -> float:
    """Round *value* up to a friendly axis maximum."""
    for step in (0.05, 0.1, 0.2, 0.25, 0.5, 1.0, 2.0, 5.0):
        if value <= step * 5:
            return math.ceil(value / step) * step
    return value


def render_chart(
    series: dict[str, list[tuple[float, float]]],
    *,
    title: str,
    x_label: str,
    y_label: str,
    parity_line: bool = True,
) -> str:
    """Return an SVG line chart for *series* (a mapping name -> [(x, y), ...])."""
    xs = [x for points in series.values() for x, _ in points]
    ys = [y for points in series.values() for _, y in points]
    x_min, x_max = min(xs), max(xs)
    y_max = _nice_max(max(ys + ([1.0] if parity_line else [])))
    y_min = 0.0

    plot_w = WIDTH - MARGIN_LEFT - MARGIN_RIGHT
    plot_h = HEIGHT - MARGIN_TOP - MARGIN_BOTTOM

    def sx(x: float) -> float:
        if x_max == x_min:
            return MARGIN_LEFT + plot_w / 2
        return MARGIN_LEFT + (x - x_min) / (x_max - x_min) * plot_w

    def sy(y: float) -> float:
        return MARGIN_TOP + (1 - (y - y_min) / (y_max - y_min)) * plot_h

    parts: list[str] = []
    parts.append(
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {WIDTH} {HEIGHT}" '
        f'font-family="system-ui, sans-serif" role="img" '
        f'aria-label="{title}">'
    )
    # Title.
    parts.append(
        f'<text x="{WIDTH / 2}" y="26" text-anchor="middle" font-size="16" '
        f'font-weight="600" fill="currentColor">{title}</text>'
    )
    # Plot frame.
    parts.append(
        f'<rect x="{MARGIN_LEFT}" y="{MARGIN_TOP}" width="{plot_w}" '
        f'height="{plot_h}" fill="none" stroke="currentColor" '
        f'stroke-opacity="0.25"/>'
    )
    # Y grid + ticks.
    if y_max <= 0.2:
        tick = 0.05
    elif y_max <= 0.5:
        tick = 0.1
    elif y_max <= 2:
        tick = 0.5
    else:
        tick = 1.0
    n = int(round(y_max / tick))
    for i in range(n + 1):
        y_val = i * tick
        yy = sy(y_val)
        parts.append(
            f'<line x1="{MARGIN_LEFT}" y1="{yy:.1f}" x2="{MARGIN_LEFT + plot_w}" '
            f'y2="{yy:.1f}" stroke="currentColor" stroke-opacity="0.08"/>'
        )
        parts.append(
            f'<text x="{MARGIN_LEFT - 8}" y="{yy + 4:.1f}" text-anchor="end" '
            f'font-size="11" fill="currentColor" fill-opacity="0.7">'
            f"{y_val:g}x</text>"
        )
    # Parity reference line at y = 1.0.
    if parity_line and y_min <= 1.0 <= y_max:
        yy = sy(1.0)
        parts.append(
            f'<line x1="{MARGIN_LEFT}" y1="{yy:.1f}" x2="{MARGIN_LEFT + plot_w}" '
            f'y2="{yy:.1f}" stroke="currentColor" stroke-opacity="0.45" '
            f'stroke-dasharray="4 3"/>'
        )
        parts.append(
            f'<text x="{MARGIN_LEFT + plot_w - 4}" y="{yy - 5:.1f}" '
            f'text-anchor="end" font-size="10" fill="currentColor" '
            f'fill-opacity="0.6">parity (1x)</text>'
        )
    # X ticks (one per distinct x value).
    for x_val in sorted(set(xs)):
        xx = sx(x_val)
        parts.append(
            f'<text x="{xx:.1f}" y="{MARGIN_TOP + plot_h + 18}" '
            f'text-anchor="middle" font-size="11" fill="currentColor" '
            f'fill-opacity="0.7">{x_val:g}</text>'
        )
    # Axis labels.
    parts.append(
        f'<text x="{MARGIN_LEFT + plot_w / 2}" y="{HEIGHT - 8}" '
        f'text-anchor="middle" font-size="12" fill="currentColor" '
        f'fill-opacity="0.8">{x_label}</text>'
    )
    parts.append(
        f'<text x="16" y="{MARGIN_TOP + plot_h / 2}" text-anchor="middle" '
        f'font-size="12" fill="currentColor" fill-opacity="0.8" '
        f'transform="rotate(-90 16 {MARGIN_TOP + plot_h / 2})">{y_label}</text>'
    )
    # Series.
    legend_y = MARGIN_TOP + 6
    for idx, (name, points) in enumerate(series.items()):
        color = SERIES_COLORS[idx % len(SERIES_COLORS)]
        ordered = sorted(points)
        path = " ".join(
            f"{'M' if i == 0 else 'L'} {sx(x):.1f} {sy(y):.1f}"
            for i, (x, y) in enumerate(ordered)
        )
        parts.append(
            f'<path d="{path}" fill="none" stroke="{color}" stroke-width="2.5"/>'
        )
        for x, y in ordered:
            parts.append(
                f'<circle cx="{sx(x):.1f}" cy="{sy(y):.1f}" r="3.5" fill="{color}"/>'
            )
        # Legend entry.
        ly = legend_y + idx * 20
        lx = MARGIN_LEFT + plot_w + 16
        parts.append(
            f'<line x1="{lx}" y1="{ly}" x2="{lx + 20}" y2="{ly}" '
            f'stroke="{color}" stroke-width="2.5"/>'
        )
        parts.append(f'<circle cx="{lx + 10}" cy="{ly}" r="3.5" fill="{color}"/>')
        parts.append(
            f'<text x="{lx + 26}" y="{ly + 4}" font-size="11" '
            f'fill="currentColor" fill-opacity="0.85">{name}</text>'
        )
    parts.append("</svg>")
    return "\n".join(parts) + "\n"


CHARTS = [
    (
        "replication-freethreaded.svg",
        REPLICATION_FREETHREADED,
        "Replication speedup - free-threaded build (3.14.2t)",
        "worker count",
        "speedup vs sequential",
    ),
    (
        "replication-gil.svg",
        REPLICATION_GIL,
        "Replication speedup - GIL build (3.14.2)",
        "worker count",
        "speedup vs sequential",
    ),
    (
        "pdes-shard-scaling.svg",
        PDES_SHARD_SCALING,
        "PDES shard scaling (3.14.2t)",
        "shard count",
        "speedup vs sequential",
    ),
    (
        "pdes-lookahead.svg",
        PDES_LOOKAHEAD,
        "PDES lookahead degradation (4-shard ring)",
        "lookahead / mean event spacing",
        "wall clock vs L=4x sequential",
    ),
]


def main() -> int:
    """Write every chart SVG into ``docs/perf/``."""
    out_dir = Path(__file__).resolve().parent.parent / "docs" / "perf"
    out_dir.mkdir(parents=True, exist_ok=True)
    for filename, series, title, x_label, y_label in CHARTS:
        parity = "lookahead" not in filename
        svg = render_chart(
            series,
            title=title,
            x_label=x_label,
            y_label=y_label,
            parity_line=parity,
        )
        (out_dir / filename).write_text(svg, encoding="utf-8")
        print(f"wrote {out_dir / filename}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
